---
- name: Deploy ZooKeeper
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp/playbooks/meta/zookeeper.yml
  tags: zk

- hosts: zk
  tasks:
    - name: Verify ZooKeeper is serving requests
      shell: echo stat | nc localhost 2181
      register: zk_status
      failed_when: "'This ZooKeeper instance is not currently serving requests' in zk_status.stdout"
      changed_when: no
      tags: zk

- name: Deploy ZooKeeper for Kafka
  import_playbook: ansible_roles/collections/ansible_collections/tosit/tdp_extra/playbooks/meta/zookeeper-kafka.yml
  tags: zk_kafka

- hosts: zk
  tasks:
    - name: Verify ZooKeeper for Kafka is serving requests
      shell: echo stat | nc localhost 2191
      register: zk_status
      failed_when: "'This ZooKeeper instance is not currently serving requests' in zk_status.stdout"
      changed_when: no
      tags: zk_kafka
